import { Metadata } from 'next';
import React from 'react'
export const metadata: Metadata = {
    title: "this is contact",
    description: "Generated by create next app",
  };
function page() {

  return (
    <div>contact</div>
  )
}

export default page