import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Comp1 from '../app/Comp1/page'
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "this is layout",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const title:string = "this is prop passed"
  return (
    <html lang="en">
      <body className={inter.className}>{children}
      <Comp1 title={title}/>
      </body>
    </html>
  );
}
